---

- hosts: all
  become: true
  roles:
     - vcs
     - php
     - nginx
     - mysql
- hosts: all
  become: true
  vars_prompt:
  - name: "githubuser"
    prompt: "Enter your github username"
    private: no
  - name: "githubpassword"
    prompt: "Enter your github password"
    private: yes
  roles:
     - git
- hosts: all
  become: true
  vars:
    installer: /tmp/installer.php
  roles:
     - composer

- hosts: all
  become: true
  roles:
     - artisan

