- name: Install MySQL
  apt:
    name: mysql-server
    state: latest
- name: Install python3-mysqldb
  apt:
     name: python3-mysqldb
     state: latest
- mysql_user:
     name: root
     password: 12345
     priv: '*.*:ALL'
     state: present
